<h3>Numpy</h3>
<ul>
<li>NumPy is a python library used for working with arrays.</li>
<li>NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.</li>
<li>The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.</li>
<li>NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.</li>
<li>This behavior is called locality of reference in computer science.</li>
<li>This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.</li>
</ul>

### Creating Arrays
<p>NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.</p>

In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [70]:
# Using Tuple
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [71]:
# Zero Dimension
import numpy as np

arr = np.array(42)

print(arr)

42


In [72]:
# One Dimension
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [73]:
# Two Dimension
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [74]:
# Three Dimension
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<br>
<code>ndim: </code>
<small>NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.</small>

In [75]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<code>ndmin: </code>
<small>An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.</small>

In [79]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


### Array Indexing
<p>Array indexing is the same as accessing an array element.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.</p>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [5]:
import numpy as np 

arr = np.array([1,2,3,4])

print(arr[3])

4


<code>Access 2-D Arrays: </code>
<small>To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.</small>

In [4]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [6]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("5th element of 2nd dim: ", arr[1,4])

5th element of 2nd dim:  10


<code>Access 3-D Arrays: </code>
<small>To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.</small>

In [8]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

10


<code>Negative Indexing: </code>
<small>Use negative indexing to access an array from the end.</small>

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Array Slicing
<p>Slicing in python means taking elements from one given index to another given index.<br>
We pass slice instead of index like this: [start:end].<br>
We can also define the step, like this: [start:end:step].</p>

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [13]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


<code>Negative Slicing: </code>
<small>Use the minus operator to refer to an index from the end</small>

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


<code>STEP: </code>
<small>Use the step value to determine the step of the slicing</small>

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


<code>Slicing 2-D Arrays</code>

In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [25]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0: ,2])

[3 8]


In [26]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0: , 1:4])

[[2 3 4]
 [7 8 9]]


### Data Types

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
<br><br>
Below is a list of all data types in NumPy and the characters used to represent them.
<br><br>
i - integer<br>
b - boolean<br>
u - unsigned integer<br>
f - float<br>
c - complex float<br>
m - timedelta<br>
M - datetime<br>
O - object<br>
S - string<br>
U - unicode string<br>
V - fixed chunk of memory for other type ( void )

<code>Checking the Data Type of an Array: </code>
<small>The NumPy array object has a property called dtype that returns the data type of the array</small>

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [29]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


<code>Creating Arrays With a Defined Data Type: </code>
<small>We use the array() function to create arrays, this function can take an optional <strong>argument: dtype</strong> that allows us to define the expected data type of the array elements</small>

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [34]:
import numpy as np 

arr = np.array([1,2,3,4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


<code>Converting Data Type on Existing Arrays: </code>
<small>The best way to change the data type of an existing array, is to make a copy of the array with the <strong>astype()</strong> method.</small>

In [37]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [39]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [40]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


### Array Copy vs View
<p>The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
<br><br>
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
<br><br>
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.</p>

<code>COPY: </code>
<small>Make a copy, change the original array, and display both arrays.</small>

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print("new array: ", arr)
print("original array: ", x)

new array:  [42  2  3  4  5]
original array:  [1 2 3 4 5]


<code>VIEW: </code>
<small>Make a view, change the original array, and display both arrays.</small>

In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print("new array: ", arr)
print("original array: ", x)

new array:  [42  2  3  4  5]
original array:  [42  2  3  4  5]


<code>Check if Array Owns it's Data: </code>
<small>Every NumPy array has the attribute base that returns None if the array owns the data.</small>

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

# The copy returns None.
print(x.base)
# The view returns the original array.
print(y.base)

None
[1 2 3 4 5]


### Array Shape
<p>NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.</p>

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

#2D with 4 elements
print(arr.shape)

(2, 4)


In [8]:
import numpy as np

arr = np.array([1,2,3,4], ndmin = 5)

#5D with 4 elements
print(arr.shape)

(1, 1, 1, 1, 4)


### Array Reshaping
<p>Reshaping means changing the shape of an array.<br>

The shape of an array is the number of elements in each dimension.<br>

By reshaping we can add or remove dimensions or change number of elements in each dimension.</p>

In [12]:
import numpy as np

arr = np.arange(1,13)

newarr = arr.reshape(4, 3)

#1D -> 2D
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
import numpy as np

arr = np.array(np.arange(1,13))

#1D -> 3D
print('3D:')
newarr = arr.reshape(2,3,2)
print(newarr)

print('\n\n')

print("4D:")
#1D -> 4D by adding 1 on leftmost side
newarr = arr.reshape(1,2,3,2)
print(newarr)

3D:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]



4D:
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]]


In [32]:
# 8 elements cannot be fitted in 3x3 matrix
# It would require 9 elements to be fitted in 3 rows and 3 columns = 3x3 = 9

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [35]:
# Copy or View

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Its a View
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


<code>Unknown Dimension: </code>
<small>You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.</small>

In [41]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

# -1 knows how many columns it has to create
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<code>Flattening the arrays: </code>
<small>Flattening array means converting a multidimensional array into a 1D array.</small>

In [45]:
# Convert the array into a 1D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

# By putting -1 it will convert into 1 Dimension array
print(newarr)

[1 2 3 4 5 6]


### Iterating Arrays
<p>Iterating means going through elements one by one.<br>

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.<br>

If we iterate on a 1-D array it will go through each element one by one.</p>

In [47]:
# Iterate on the elements of the following 1-D array

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [48]:
#Iterate on the elements of the following 2-D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [51]:
# Iterate on each scalar element of the 2-D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [55]:
# Iterate on the elements of the following 3-D array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [59]:
# Iterate down to the scalars

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


<code>Iterating Arrays Using nditer(): </code>
<small>The function nditer() is a helping function that can be used from very basic to very advanced iterations.</small> 

In [57]:
# Iterate through the following 3-D array

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [61]:
# In previous to previous example we have use 3 for loops 
# So now we can use only 1 for loop to get the result

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


<code>Iterating Array With Different Data Types: </code>
<small>We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.</small>

In [65]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


<code>Iterating With Different Step Size: </code>
<small>We can use filtering and followed by iteration.</small>

In [66]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


<code>Enumerated Iteration Using ndenumerate(): </code>
<small>Enumeration means mentioning sequence number of somethings one by one.</small>

In [69]:
# Enumerate on following 1D arrays elements

import numpy as np

arr = np.array([1, 2, 3])

for i, x in np.ndenumerate(arr):
  print(i, x)

(0,) 1
(1,) 2
(2,) 3


In [70]:
# Enumerate on following 2D arrays elements

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i, x in np.ndenumerate(arr):
    print(i, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining NumPy Arrays
<p>Joining means putting contents of two or more arrays in a single array.<br><br>
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.</p>

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [4]:
# Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


<code>Joining Arrays Using Stack Functions: </code>
<small>Stacking is same as concatenation, the only difference is that stacking is done along a new axis.</small>

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


<code>Stacking Along Rows: </code>
<small>NumPy provides a helper function: hstack() to stack along rows.</small>

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


<code>Stacking Along Columns: </code>
<small>NumPy provides a helper function: vstack()  to stack along columns.</small>

In [12]:
import numpy as np

arr1 = np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

arr = np.vstack((arr1,arr2))

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


<code>Stacking Along Height (depth): </code>
<small>NumPy provides a helper function: dstack() to stack along height, which is the same as depth.</small>

In [15]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting NumPy Arrays
<p>
Splitting is reverse operation of Joining.<br>
    
Joining merges multiple arrays into one and Splitting breaks one array into multiple.<br>
    
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
<p>

In [20]:
# Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [23]:
# Split the array in 4 parts:

import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


<code>Split Into Arrays: </code>
<small>The return value of the array_split() method is an array containing each of the split as an array.</small>

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


<code>Splitting 2-D Arrays: </code>
<small>Use the same syntax when splitting 2-D arrays.</small>

In [25]:
# Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


### Searching Arrays
<p>You can search an array for a certain value, and return the indexes that get a match.<br>
    
To search an array, use the where() method.</p>

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 7, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 7], dtype=int32),)


In [30]:
# Find the indexes where the values are even:

import numpy as np

arr = np.array(list(range(0,11)))

x = np.where(arr%2 == 0)

print(x)

(array([ 0,  2,  4,  6,  8, 10], dtype=int32),)


In [34]:
# Find the indexes where the values are odd:

import numpy as np

arr = np.array(list(range(0,11)))

x = np.where(arr%2 != 0)

print(x)

(array([1, 3, 5, 7, 9], dtype=int32),)


<code>Search Sorted: </code>
<small>There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.</small>

In [36]:
import numpy as np

arr = np.array([6, 8, 9, 7])

x = np.searchsorted(arr, 7)

print(x)

1


In [37]:
import numpy as np

arr = np.array([6, 8, 9, 7])

x = np.searchsorted(arr, 7, side='right')

# searching start from right side
print(x)

2


In [39]:
# multiple values

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

# returns the position where these value will be inserted
print(x)

[1 2 3]


### Sorting Arrays
<p>Sorting means putting elements in a ordered sequence.<br>

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.<br>

The NumPy ndarray object has a function called sort(), that will sort a specified array.</p>

In [41]:
# Numbers

import numpy as np

arr = np.array([3, 2, 0, 1])

# sort the above array
print(np.sort(arr))

[0 1 2 3]


In [43]:
# Strings

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [44]:
# Boolean

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


<code>Sorting a 2-D Array: </code>
<small>If you use the sort() method on a 2-D array, both arrays will be sorted.</small>

In [45]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filtering Arrays
<p>Getting some elements out of an existing array and creating a new array out of them is called filtering.<br>

In NumPy, you filter an array using a boolean index list.</p>

In [49]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

# print only numbers which are True
print(newarr)

[41 43]


In [50]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [57]:
# Create a filter array that will return only even elements from the original array:
# Method 1

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [58]:
# Method 2

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filter_arr = (arr%2 == 0)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
